# This workflow will be triggered on all Pull Requests from fork-repo/feature-branch to organization-repo/main-branch.
# Validates the Packer AMI templates

name: Packer AMI template validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate packer template for the custom AMI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create & configure Packer variables
        run: |
          touch ami.pkrvars.hcl
          echo ami_prefix=\"${{ vars.AMI_PREFIX }}\" >> ami.pkrvars.hcl
          echo OS=\"${{ vars.OS }}\" >> ami.pkrvars.hcl
          echo ubuntu_version=\"${{ vars.UBUNTU_VERSION }}\" >> ami.pkrvars.hcl
          echo ssh_username=\"${{ vars.SSH_USERNAME }}\" >> ami.pkrvars.hcl
          echo subnet_id=\"${{ secrets.SUBNET_ID }}\" >> ami.pkrvars.hcl
          echo source_ami=\"${{ vars.SOURCE_AMI }}\" >> ami.pkrvars.hcl
          echo aws_region=\"${{ vars.AWS_REGION }}\" >> ami.pkrvars.hcl
          echo instance_type=\"${{ vars.INSTANCE_TYPE}}\" >> ami.pkrvars.hcl
          echo volume_size=\"${{ vars.VOLUME_SIZE}}\" >> ami.pkrvars.hcl
          echo volume_type=\"${{ vars.VOLUME_TYPE}}\" >> ami.pkrvars.hcl
          echo device_name=\"${{ vars.DEVICE_NAME}}\" >> ami.pkrvars.hcl

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer init
        id: init
        run: "packer init packer/template/jenkins-ami-template.pkr.hcl"

      - name: Packer format
        id: fmt
        run: "packer fmt packer/template/jenkins-ami-template.pkr.hcl"

      - name: Validate packer template
        id: validate
        run: "packer validate \
          -var 'ami_users=${{ secrets.AMI_USERS }}' \
          --var-file=ami.pkrvars.hcl packer/template/jenkins-ami-template.pkr.hcl"