# This workflow will be triggered to build the custom Jenkins AMI using Packer
name: Build Jenkins AMI using Packer

on:
  push:
    branches: [main]

jobs:
  packer_build_image:
    runs-on: ubuntu-latest
#    environment: ${{ vars.ENVIRONMENT }}
    name: Build AWS Custom AMI for Jenkins with Caddy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Prepare Jenkins Configuration as Code file and DSL job
        run: |
          sed -i 's/ADMIN_USER/${{ secrets.JENKINS_ADMIN_USER }}/g' jenkins/jenkins-config-as-code.yaml
          sed -i 's/ADMIN_PASSWORD/${{ secrets.JENKINS_ADMIN_PASSWORD }}/g' jenkins/jenkins-config-as-code.yaml
          sed -i 's/G_PAT/${{ secrets.G_PAT }}/g' jenkins/jenkins-config-as-code.yaml
          sed -i 's/G_USERNAME/${{ secrets.G_USERNAME }}/g' jenkins/jenkins-config-as-code.yaml
          sed -i 's/DOCKER_TOKEN/${{ secrets.DOCKER_TOKEN }}/g' jenkins/jenkins-config-as-code.yaml
          sed -i 's/DOCKER_USERNAME/${{ secrets.DOCKER_USERNAME }}/g' jenkins/jenkins-config-as-code.yaml
          sed -i 's/G_USERNAME/${{ secrets.G_USERNAME }}/g' jenkins/build-and-push-static-site.groovy
          sed -i 's/DOCKER_USERNAME/${{ secrets.DOCKER_USERNAME }}/g' jenkins/build-and-push-static-site.groovy
          sed -i 's/DOCKER_PASSWORD/${{ secrets.DOCKER_PASSWORD }}/g' jenkins/build-and-push-static-site.groovy
          sed -i 's/BUILD_NO/${{ github.run_number }}/g' jenkins/build-and-push-static-site.groovy
          sed -i 's/DOCKERHUB_REPO/${{ secrets.DOCKERHUB_REPO }}/g' jenkins/build-and-push-static-site.groovy
        shell: bash

#      - name: Replace placeholders in Jenkins DSL script
#        run: |
#          sed -i 's/${G_USERNAME}/${{ secrets.G_USERNAME }}/g' jenkins/build-and-push-static-site.groovy
#          sed -i 's/${G_CREDENTIALS_ID}/${{ secrets.G_CREDENTIALS_ID }}/g' jenkins/build-and-push-static-site.groovy
#          sed -i 's/${DOCKER_USERNAME}/${{ secrets.DOCKER_USERNAME }}/g' jenkins/build-and-push-static-site.groovy
#          sed -i 's/${DOCKER_CREDENTIALS_ID}/${{ secrets.DOCKER_CREDENTIALS_ID }}/g' jenkins/build-and-push-static-site.groovy
#        shell: bash

      - name: Create & configure Packer variables
        run: |
          touch jenkins-ami.pkrvars.hcl
          echo ami_prefix=\"${{ vars.AMI_PREFIX }}\" >> jenkins-ami.pkrvars.hcl
          echo OS=\"${{ vars.OS }}\" >> jenkins-ami.pkrvars.hcl
          echo ubuntu_version=\"${{ vars.UBUNTU_VERSION }}\" >> jenkins-ami.pkrvars.hcl
          echo ssh_username=\"${{ vars.SSH_USERNAME }}\" >> jenkins-ami.pkrvars.hcl
          echo subnet_id=\"${{ secrets.SUBNET_ID }}\" >> jenkins-ami.pkrvars.hcl
          echo source_ami=\"${{ vars.SOURCE_AMI }}\" >> jenkins-ami.pkrvars.hcl
          echo aws_region=\"${{ vars.AWS_REGION }}\" >> jenkins-ami.pkrvars.hcl
          echo instance_type=\"${{ vars.INSTANCE_TYPE}}\" >> jenkins-ami.pkrvars.hcl
          echo volume_size=\"${{ vars.VOLUME_SIZE}}\" >> jenkins-ami.pkrvars.hcl
          echo volume_type=\"${{ vars.VOLUME_TYPE}}\" >> jenkins-ami.pkrvars.hcl
          echo device_name=\"${{ vars.DEVICE_NAME}}\" >> jenkins-ami.pkrvars.hcl

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer init
        id: init
        run: "packer init packer/template/jenkins-ami-template.pkr.hcl"

      - name: Packer format
        id: fmt
        run: "packer fmt packer/template/jenkins-ami-template.pkr.hcl"

      - name: Validate packer template
        id: validate
        run: "packer validate \
          -var 'ami_users=${{ secrets.AMI_USERS }}' \
          --var-file=jenkins-ami.pkrvars.hcl packer/template/jenkins-ami-template.pkr.hcl"

      - name: Build AMI using Packer
        id: build
        run: "packer build \
          -var 'ami_users=${{ secrets.AMI_USERS }}' \
          --var-file=jenkins-ami.pkrvars.hcl packer/template/jenkins-ami-template.pkr.hcl"