name: Packer AMI template validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate packer template for the custom AMI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer Init
        run: |
          cd packer/template
          packer init jenkins-ami-template.pkr.hcl

      - name: Packer Format
        run: |
          cd packer/template
          packer fmt -check .

      - name: Validate Packer template
        id: validate
        run: 
          packer validate -var "ami_users=${{ secrets.AMI_USERS }}" packer/template/jenkins-ami-template.pkr.hcl