# This workflow will be triggered on all Pull Requests from fork-repo/feature-branch to organization-repo/main-branch.
# Validates the Packer AMI templates

name: Packer AMI template validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate packer template for the custom AMI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create & configure Packer variables
        run: |
          cd packer/template
          touch jenkins-ami.pkrvars.hcl
          echo ami_prefix=\"${{ vars.AMI_PREFIX }}\" >> jenkins-ami.pkrvars.hcl
          echo OS=\"${{ vars.OS }}\" >> jenkins-ami.pkrvars.hcl
          echo ubuntu_version=\"${{ vars.UBUNTU_VERSION }}\" >> jenkins-ami.pkrvars.hcl
          echo ssh_username=\"${{ vars.SSH_USERNAME }}\" >> jenkins-ami.pkrvars.hcl
          echo subnet_id=\"${{ secrets.SUBNET_ID }}\" >> jenkins-ami.pkrvars.hcl
          echo source_ami=\"${{ vars.SOURCE_AMI }}\" >> jenkins-ami.pkrvars.hcl
          echo aws_region=\"${{ vars.AWS_REGION }}\" >> jenkins-ami.pkrvars.hcl
          echo instance_type=\"${{ vars.INSTANCE_TYPE}}\" >> jenkins-ami.pkrvars.hcl
          echo volume_size=\"${{ vars.VOLUME_SIZE}}\" >> jenkins-ami.pkrvars.hcl
          echo volume_type=\"${{ vars.VOLUME_TYPE}}\" >> jenkins-ami.pkrvars.hcl
          echo device_name=\"${{ vars.DEVICE_NAME}}\" >> jenkins-ami.pkrvars.hcl

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer Init
        run: |
          cd packer/template
          packer init jenkins-ami-template.pkr.hcl

      - name: Packer Format
        run: |
          cd packer/template
          packer fmt -check .

      - name: Validate Packer template
        id: validate
        run: |
          cd packer/template
          packer validate -var 'ami_users=${{ secrets.AMI_USERS }}' --var-file=jenkins-ami.pkrvars.hcl jenkins-ami-template.pkr.hcl"